POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "cchura.cpc@gmail.com",
    "password": "cristian123"
}

###

GET http://127.0.0.1:8000/api/auth/perfil
Accept: application/json
Authorization: Bearer 30|EtjLF1wS3ELm3oNIO6wwDVvDWvdAbpY0e5KmhyeE

###

GET http://127.0.0.1:8000/api/categoria
Accept: application/json
Authorization: Bearer 32|CBw6XzlFOjQiqoIoyBSVUiszfhvVmntF2AVH2DzT
